### ISSUE TITLE
Add more details in README, please

### ISSUE THREAD

**Issue by ldfinfontainebleau** [Tauranis/deep_coffee#4]
Thank u for your job! It is interesting! But I am confused while see this project's README, what does this project done? select coffe beans bbox(like object detection)? or recognize good or bad coffe beans?

**Comment by Tauranis** [comment]
Hi @ldfinfontainebleau . Thanks for the intereset on this.

My apologies if the README is not that specific. Actually is contains only the instructions to make the code to work. There is no description about the problem itself. I'm gonna improve it. But in meanwhile you can read this [Medium Post](https://medium.com/swlh/automation-for-coffee-bean-selection-79a6b32b88de) where I explain the problem completely.

In a nutshell, the endgame is about classify good and bad beans for automatical quality control. The intermediate steps is about some image processing algorithms, such as thresholding, bbox estimation (like object detection).

I chose not to use object detection algorithms because the use case has very controlled environment, like homogeneous  background, high contrast between background & foreground, lightening conditions and non-overlapping objects. Although an object detection would work perfectly, it would be like using a bazooka to kill an ant. 
I wanted to show that computer vision is not only about deep learning.
We can solve simple problems with simple approaches.

**Comment by ldfinfontainebleau** [comment]
> Hi @ldfinfontainebleau . Thanks for the intereset on this.
> 
> My apologies if the README is not that specific. Actually is contains only the instructions to make the code to work. There is no description about the problem itself. I'm gonna improve it. But in meanwhile you can read this [Medium Post](https://medium.com/swlh/automation-for-coffee-bean-selection-79a6b32b88de) where I explain the problem completely.
> 
> In a nutshell, the endgame is about classify good and bad beans for automatical quality control. The intermediate steps is about some image processing algorithms, such as thresholding, bbox estimation (like object detection).
> 
> I chose not to use object detection algorithms because the use case has very controlled environment, like homogeneous background, high contrast between background & foreground, lightening conditions and non-overlapping objects. Although an object detection would work perfectly, it would be like using a bazooka to kill an ant.
> I wanted to show that computer vision is not only about deep learning.
> We can solve simple problems with simple approaches.

Thank you for your reply!
I was confused by word "deep" in your title. While ths cases in sample scenario really do not need deep learning, I am trying do some work on  coffee beans detection & recognition with uncertain background. It seems that object detection models in deep learning maybe useful.
: )

**Comment by Tauranis** [comment]
Nice, do you have any material on that?
